export type IPlayer = {
    id: number,
    name: string,
    tournament: string,
    stages: string,
    match_type: string,
    team: string,
    agents: string[],
    rounds_played: number,
    rating: number,
    acs: number,
    kd: number,
    kast: number,
    adr: number | string,
    kpr: number,
    apr: number,
    fkpr: number | string,
    fdpr: number | string,
    hs: number,
    clutch_success: number,
    clutches: string | string,
    max_kills: number,
    kills: number,
    deaths: number,
    assists: number,
    fk: number,
    fd: number,
    photo: string
};